### ISSUE TITLE
Auto discover name of script

### ISSUE THREAD

**Issue by developius** [popey456963/logger#2]
You could use `__filename` to automatically decide what to use in the second part of the logger info:
`[21:42:32] [app.js] I'm informing you of something`

**Comment by popey456963** [comment]
Tried this before, however `__filename` refers to the module file name (in this case of log-js), which is always `index.js`.  Alternatively, you can do `require("log-js")(__filename)`.  

I am looking into a new method of doing this, it would be very useful.  Added to 1.6.0 Release.

**Comment by popey456963** [comment]
Fixed in the referenced commit.  Found out about `module.parent.filename`, a surprisingly useful thing.

**Comment by developius** [comment]
Awesome.
